---
# This playbook will create pv, vg, lv and file system.

#- name: Creare Physical Volume
#  command: pvcreate {{ pv_name }}

- name: Create Volume Group
  lvg: vg={{ vg_name }} pvs={{ pv_name }} pesize=16

- name: Create Logical Volume
  lvol: vg={{ vg_name }} lv={{ lv_name }} size={{ lv_size }}

- name: Create File system
  filesystem: dev=/dev/{{ vg_name }}/{{ lv_name }} fstype=ext4 resizefs=yes

- name: Mount the File system
  mount:
    path={{ fs_name }}
    src=/dev/{{ vg_name }}/{{ lv_name }}
    fstype=ext4
    state=mounted

- name: Changing file system permission
  file:
    path={{ fs_name }}
    mode=0765
